### PR TITLE
adding label to metadata field

### PR DESCRIPTION
**Pull request by totalys**
Adding a label to indicate Metadata field

### CODE REVIEW

**Comment by totalys** [comment]
image

**Comment by huynhminhtan** [comment]
Hi @totalys,

Thanks for your pull request again, that is awesome 👏 👏 👏 .

Humm, you can check the valid user name on Github for the commit of this pull request, after the merge is successful you will be among the project contributors. (You can close this pull request and open another pull request with a valid user name if you want).

---
image

**Comment by totalys** [comment]
Oh, Sorry, I guess I used my company's account. I'll chance it right now.

**Comment by huynhminhtan** [comment]
Thanks for the enhancement. It has been merged into master.

**Pull request merged**
