### PR TITLE
gRPCSampler Metadata can be Json String 

### PR DESCRIPTION
**Pull request by Jayrajgondaliya**
Screen Shot 2021-12-04 at 5 20 56 PM

### CODE REVIEW

**Comment by huynhminhtan** [comment]
Hi @Jayrajgondaliya, thank you for your pull request that will support the JSON option when using metadata.

It will be great if you add a test case for JSON support that is helpful to know how it works. And, an existing test case _testCanThrowExceptionWithInvalidMetaData_ was failed, you can edit the exception message for the test pass. Finally, could you please update the README under Configurations -> Metadata, which describes how to use the JSON format?

Thanks for your contribution. Best Regards. 🎉🎉🎉

**Comment by Jayrajgondaliya** [comment]
Hi @huynhminhtan, thanks for the feedback, 
I have Added Test cases, Modified Failing test cases, and added Details in README.md.

Thanks,

**Comment by huynhminhtan** [comment]
Hi @Jayrajgondaliya, thanks for the enhancement.

Just a little bit more, test cases _testCanListAllMethodsInProtoWithNullLibFolderPath_  and _testCanListAllMethodsInProtoWithoutExternalLibs_ whose methods in the list may be out of order when assertion. 
I also try to push the tiny fix but don't have permission. Could you please update the test cases for success. Thanks.

Little tip!

```java
@Test
public void testCanListAllMethodsInProtoWithoutExternalLibs() {
...

   // Assertion
 + Collections.sort(list);
 + Collections.sort(methods);
   Assert.assertEquals(list, methods);
}
```

**Comment by huynhminhtan** [comment]
Hi @Jayrajgondaliya, thanks for the enhancement. It has been merged into master. 🎉🎉🎉

**Pull request merged**
