### PR TITLE
fix: error invalid call sequence with exception in initiated gRPC request

### PR DESCRIPTION
**Pull request by minhhoangvn**

### CODE REVIEW

**Comment by minhhoangvn** [comment]
fix #96 #99

**Comment by minhhoangvn** [comment]
Hi @yl-yue  that happened when I added a unit test for that plugin you can see the data is in 2021, not in 2022. Besides, we will set up a pre-commit-hooks with pretty-format-java for this repository to make sure we will not have any merge conflict related to code format. 
image

**Comment by yl-yue** [comment]
Thank you for your understanding. When I pulled the code this time, I found hundreds of more submissions, which made me very confused, and there were many conflicts with my local (because I had some unsubmitted codes).

**Comment by minhhoangvn** [comment]
:D You need to sync up with the upstream repo more frequently, currently this repo may have high commit

**Pull request merged**
