### PR TITLE
Resolve page stutter caused by request mock

### PR DESCRIPTION
**Pull request by yl-yue**
https://github.com/zalopay-oss/jmeter-grpc-request/pull/82#issuecomment-994431910

### CODE REVIEW

**Comment by yl-yue** [comment]
@huynhminhtan Hello, if possible, please merge this PR, because I will submit a new PR, and the new PR will solve other problems and new features

**Comment by huynhminhtan** [comment]
Hi @yl-yue, yeap you can create another merge request, this request will be merged into master soon. Thank you for all your contributions.

**Comment by yl-yue** [comment]
New Pull Requests will be launched to implement the following features:
- Fix helpPage address, (① Old address is invalid, new address points to Github)
- add getServiceResolver cache
- New JMeterVariableUtils for manipulating user variables in GUI
- Proto root directory already supports the user variable '${}' (②③ Click Listing in GUI, error is reported because user variable is not loaded)

image

Wait for pr #83 to merge

**Comment by huynhminhtan** [comment]
Hi @yl-yue, I'm sorry for the late response.

Yeap. It's a nice enhancement by checking the condition before creating mock data. Thanks for the PR.

**Pull request merged**
